name: Build and Push

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Test
        run: |
          npm ci
          npm test
      - name: Build
        run: npm run build
      - name: git setting
        run: |
          git config --local user.email "ivgtr.me@gmail.com"
          git config --local user.name "ivgtr"
          git add .
          git commit -m "🤖 run: CI Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
