name: Get luvData

on:
  # schedule:
  #   - cron: "0 5,17 * * *"
  push:
    branches: [master]

jobs:
  working-luvT-archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    timeout-minutes: 15
    steps:
      - name: working luvT-archive!
        run: npm run workflow
        env:
          TZ: Asia/Tokyo
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          SHEET_NAME: s2luv-sheet
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SERVICE_CLIENT_EMAIL: ${{ secrets.SERVICE_CLIENT_EMAIL }}
          SERVICE_PRIVATE_KEY: ${{ secrets.SERVICE_PRIVATE_KEY }}
