name: Save to Love Tweet Working

on:
  schedule:
    - cron: "0 5,17 * * *"

jobs:
  working-luvT-archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: working luvT-archive!
        run: |
          node dist/index.js
        env:
          TZ: Asia/Tokyo
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          SHEET_NAME: s2luv-sheet
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SERVICE_CLIENT_EMAIL: ${{ secrets.SERVICE_CLIENT_EMAIL }}
          SERVICE_PRIVATE_KEY: ${{ secrets.SERVICE_PRIVATE_KEY }}
