name: CI

on:
  schedule:
    - cron: '0 5,17 * * *'

jobs:
  working-luvT-archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: working luvT-archive!
        run: yarn workflow
        env:
          TZ: Asia/Tokyo
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          SHEET_NAME: s2luv-sheet
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SERVICE_CLIENT_EMAIL: ${{ secrets.SERVICE_CLIENT_EMAIL }}
          SERVICE_PRIVATE_KEY: ${{ secrets.SERVICE_PRIVATE_KEY }}
